language: node_js

node_js:
  - '10'

branches:
  only:
    - master

sudo: required

script:
- npm install
- npm run build
- ssh-keyscan -H $DEPLOY_SSH_ADDRESS >> ~/.ssh/known_hosts
- chmod 600 ~/.ssh/2018_2_DeadMolesStudio_id_rsa.pem
- scp -r -i ~/.ssh/2018_2_DeadMolesStudio_id_rsa.pem ./public root@$DEPLOY_SSH_ADDRESS:/opt/dmstudio/site

before_install:
- openssl aes-256-cbc -K $encrypted_dba14a8eacc6_key -iv $encrypted_dba14a8eacc6_iv
  -in 2018_2_DeadMolesStudio_id_rsa.pem.enc -out ~/.ssh/2018_2_DeadMolesStudio_id_rsa.pem
  -d
